import { StrictMode, useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowDownRight, ArrowUpRight, CalendarDays, Check, ChevronRight, Download, ExternalLink, Flag, Menu, Shield, Sparkles, Target, X } from 'lucide-react';
import './styles.css';

const entries = [
  { id: 'nda', letter: 'A', name: 'NDA', fullName: 'National Defence Academy', accent: 'forest', descriptor: 'The earliest, broadest door', age: '16½ – 19½ years', qualification: 'Class 12 pass or appearing (any stream, for Army wing)', training: '3 years at NDA, Khadakwasla → 1 year at IMA Dehradun (4 years total)', selection: 'UPSC written exam (Maths + General Ability) → SSB Interview → Medical', commission: 'Permanent Commission, confirmed', whyTitle: "Why It's the Best Entry", why: "Longest grooming time of any route, and the widest choice of Arms & Services — including the Corps of Signals — decided at the end by merit and preference. He isn't locked into a technical stream early." },
  { id: 'tes', letter: 'B', name: 'TES', fullName: '10+2 Technical Entry Scheme', accent: 'sage', descriptor: 'Direct to engineering', age: '16½ – 19½ years', qualification: 'Class 12 with PCM, minimum 60% aggregate, plus a valid JEE (Mains) score', training: '3 years B.Tech at CME Pune / MCEME Secunderabad / MCTE Mhow → 1 year IMA (4 years total)', selection: 'Shortlist on 12th PCM% + JEE Mains rank → SSB Interview → Medical (no written exam)', commission: 'Permanent Commission, rank of Lieutenant', whyTitle: 'Signals Advantage', why: "TES is one of the direct feeder entries into the Corps of Signals, Corps of Engineers and EME. Strong PCM / JEE performance genuinely improves his shot at a technical Arm, if that's where his interest lies." },
  { id: 'cds', letter: 'C', name: 'CDS (IMA)', fullName: 'Combined Defence Services — IMA', accent: 'brass', descriptor: 'The graduate-entry route into IMA', age: '19 – 24 years', qualification: 'Graduation in any discipline from a recognised university; final-year students may also apply', training: '1.5 years at IMA, Dehradun — same academy and same PC status as NDA cadets', selection: 'UPSC written exam → SSB Interview → Medical', commission: 'Permanent Commission (IMA is PC-only; OTA under CDS is SSC and is excluded here)', whyTitle: 'Why It Matters', why: 'The natural backup / second chance if NDA or TES do not work out. It is a twice-a-year exam with a wide, multi-year eligibility window — a generous safety net running well into his twenties.' },
  { id: 'tgc', letter: 'D', name: 'TGC', fullName: 'Technical Graduate Course', accent: 'clay', descriptor: 'Direct entry for engineers', age: '20 – 27 years', qualification: 'BE / B.Tech (or final year) in a notified engineering discipline', training: '1 year at IMA, Dehradun — shorter than CDS, plus 1 year ante-date seniority as a reward for his engineering degree', selection: 'Shortlist on engineering marks → SSB Interview → Medical (no written exam)', commission: 'Permanent Commission, rank of Lieutenant', whyTitle: 'Signals Advantage', why: "Like TES, TGC is a preferred feeder for Signals, EME and Engineers. An Electronics / Comm / CS / IT engineering degree is a genuine edge here — and this window stays open the longest of all four entries." },
];

const entryDetails = {
  nda: {
    overview: 'NDA is the first and broadest Permanent Commission route. For the Army wing, a student can apply from any Class 12 stream, so he does not have to commit to engineering before knowing where his strengths lie.',
    selection: 'The UPSC written exam has Mathematics and General Ability sections. Candidates who clear the written cut-off are called for the five-day SSB process, followed by medical examination and final merit based on performance, vacancies and preference.',
    training: 'Selected candidates spend three years at NDA, Khadakwasla with joint-services academic, physical and military training, then one year at IMA, Dehradun. This produces the longest officer-development runway of the four routes.',
    prepare: 'Build Maths, English, general knowledge, communication, fitness and leadership habits early. The practical target is to make NDA preparation part of school life rather than treating it as a last-minute exam project.',
  },
  tes: {
    overview: 'TES is the direct technical route after Class 12. It is best suited to a student who is comfortable with PCM and wants an engineering degree while keeping a direct path to Permanent Commission open.',
    selection: 'There is no separate written TES exam. Shortlisting is based on Class 12 PCM performance and a valid JEE Main score, after which the candidate goes through SSB and medical examination. A minimum 60% PCM aggregate is an important planning threshold.',
    training: 'Training combines three years of engineering education at CME Pune, MCEME Secunderabad or MCTE Mhow with one year at IMA. The technical education is not a detour: it is part of the officer-entry pipeline.',
    prepare: 'Keep PCM marks strong, prepare seriously for JEE Main and maintain the same fitness, communication and SSB habits needed for NDA. TES should run in parallel with NDA, not replace it.',
  },
  cds: {
    overview: 'CDS (IMA) is the graduate-entry safety net. It accepts a recognised graduation degree and final-year students can apply, making it useful even if the school-leaving entries do not work out.',
    selection: 'UPSC conducts the written exam, followed by SSB Interview and medical examination. The IMA option is the Permanent Commission route; OTA under CDS is Short Service Commission and is deliberately excluded from this plan.',
    training: 'The IMA course is approximately 1.5 years at Dehradun. It leads to the same Permanent Commission status as the NDA route, but with a shorter, more focused training period because the candidate joins after graduation.',
    prepare: 'Use the engineering or graduation years to protect academic performance, build current-affairs and English depth, maintain fitness, and begin serious SSB preparation through interviews, group tasks and psychology practice.',
  },
  tgc: {
    overview: 'TGC is the longest-running age window and the direct engineering graduate route. It is especially valuable as a late-career backup because applications can remain possible through the final year of the 20–27 age band.',
    selection: 'There is no UPSC written exam. Candidates are shortlisted using engineering marks in a notified discipline, then face SSB and medical examination. Final eligibility depends on the course notification and listed engineering branches.',
    training: 'Training is one year at IMA. An engineering degree also brings one year of ante-date seniority as a reward, making this a shorter route into the same officer career while preserving technical options such as Signals, EME and Engineers.',
    prepare: 'Choose a relevant engineering discipline, keep marks consistently strong, track notified branches each cycle, stay medically fit and apply every eligible cycle from final year onward instead of waiting for one perfect attempt.',
  },
};

const attempts = [
  ['NDA', '16½–19½ yrs', '20 Mar 2028 – 20 Mar 2031', '4 solid attempts', "NDA II'28, NDA I'29, NDA II'29, NDA I'30"],
  ['TES', '16½–19½ yrs', '20 Mar 2028 – 20 Mar 2031', '3–4 attempts, parallel to NDA', 'Same cycles, from Class 12 (2028–29) onward'],
  ['CDS (IMA)', '19–24 yrs', '~20 Sep 2030 – 20 Sep 2035', '6–8 attempts (twice/yr)', 'From final year of degree (~2032) through 2035'],
  ['TGC', '20–27 yrs', '~20 Sep 2031 – 20 Sep 2038', 'Many cycles available', 'From final year of degree (~2032) through 2038'],
];

const timelineA = [
  ['2026', '14–15', 'Class 10 (now)', '—', 'Foundation phase — start fitness routine and Maths/GK groundwork'],
  ['2027', '15–16', 'Class 11', '—', 'Lock PCM if leaning TES; begin structured NDA-pattern practice'],
  ['2028', '16–17', 'Class 12 (from April)', 'NDA II 2028 (Sept)', "His first real attempt — 12th-appearing satisfies the qualification"],
  ['2029', '17–18', 'Class 12 boards (Jan–Mar) → degree begins', 'NDA I 2029 (Apr), NDA II 2029 (Sept), JEE Mains', 'Biggest year — boards, JEE Mains, and two NDA sittings'],
  ['2030', '18–19', 'Degree Year 1–2', 'NDA I 2030 (Apr) — last shot', 'CDS-IMA minimum age (19) crossed this year'],
  ['2031', '19–20', 'Degree Year 2–3', '—', 'TGC minimum age (20) reached; NDA/TES window has closed'],
  ['2032', '20–21', 'Degree Year 3–4 (final year)', 'CDS & TGC (if final year)', 'First graduate-entry attempts begin, provisionally as a final-year student'],
];
const timelineB = [
  ['2033', '21–22', 'Graduated (engineering)', 'CDS, TGC', 'Both entries running fully in parallel'],
  ['2034', '22–23', 'Early career / postgrad', 'CDS, TGC', '—'],
  ['2035', '23–24', 'Early career / postgrad', 'CDS (last eligible year), TGC', 'Last realistic chance for CDS–IMA'],
  ['2036', '24–25', 'Career', 'TGC only', 'CDS window has closed'],
  ['2037', '25–26', 'Career', 'TGC only', '—'],
  ['2038', '26–27', 'Career', 'TGC (last eligible year)', 'Final PC door before age 27 closes'],
];

const prepRows = [
  ['Now — Class 10 (2026–27)', "Build Maths + English fluency for NDA's General Ability paper. Start a daily fitness routine (push-ups, sit-ups, running) aimed at SSB physical standards. Add light daily current-affairs reading."],
  ['Class 11 (2027–28)', 'Firm up PCM if leaning toward TES. Begin structured NDA written-exam mock tests. Track his 1.6 km run timing against SSB benchmarks.'],
  ['Class 12 (2028–29)', 'Sit NDA II 2028 in September — his first real attempt. Prep JEE Mains (Jan/Apr 2029) in parallel for TES. Keep PCM aggregate above 60% for TES eligibility. Attempt NDA I 2029 right after boards.'],
  ['Post-12th (2029–30)', 'Attempt NDA II 2029 and NDA I 2030 while starting his engineering degree. If selected at any point, he joins NDA or CME immediately — training begins right away.'],
  ['Engineering degree (2030–33)', 'Keep marks strong — TGC shortlists on engineering marks alone. Maintain fitness continuously. From 2nd–3rd year, start SSB-specific prep: group tasks, psychology tests, mock interviews.'],
  ['Final year onward (2032+)', 'Apply for CDS and TGC every single cycle. Stay on top of medical fitness — eyesight, BMI, dental — the most common reason candidates get dropped after clearing the SSB.'],
];

const strategyOne = [
  ['Focus on NDA first', "It's the broadest entry (any stream), gives the longest training and the best-known SSB conversion track record, and keeps every Arm — including Signals — open based on final merit."],
  ['Run TES in parallel, not instead', 'If he studies PCM and keeps JEE Mains prep going anyway (which also helps NDA’s Maths paper), TES essentially comes free alongside NDA prep — no extra written exam needed.'],
  ['4 real attempts, 2028–2030', "NDA II 2028, NDA I & II 2029, and NDA I 2030 — the widest opening he will have, with the first one arriving as soon as he starts Class 12."],
];
const finalTakeaways = [
  'Give NDA everything from September 2028 (his first attempt) through 2030 — it is the widest door and the longest, most complete training.',
  'Run TES alongside it for free, since PCM / JEE prep overlaps with NDA prep.',
  'Choose an engineering degree as his fallback path — the only choice that keeps both CDS and TGC open later.',
  'From 2032 onward, attack CDS and TGC together every cycle until 2035 (CDS closes at 24) and 2038 (TGC closes at 27).',
];

const selectionStages = [
  ['01', 'Build eligibility', 'Protect the academic requirement first: Class 12, PCM and JEE for TES, graduation for CDS, or engineering marks for TGC.'],
  ['02', 'Clear the entry filter', 'NDA and CDS use a UPSC written exam. TES and TGC shortlist candidates through academic performance and the relevant score or branch notification.'],
  ['03', 'Prove officer potential', 'SSB tests intelligence, communication, initiative, teamwork, responsibility, adaptability and decisions under pressure.'],
  ['04', 'Clear medical and merit', 'Medical fitness, vacancies, merit and preferences decide the final joining outcome. Clearing one stage alone is not the same as selection.'],
];
const ssbPoints = [
  ['Day 1–2', 'Screening and testing', 'Intelligence testing, picture perception and discussion tasks create the first filter. Listening and teamwork matter as much as speaking.'],
  ['Day 2–4', 'Psychology and group tasks', 'The board observes planning, practical thinking, cooperation, responsibility and how naturally a candidate contributes without dominating.'],
  ['Day 4–5', 'Interview and conference', 'The interview checks consistency between the application, academics, interests, life story and answers. Honest, specific answers beat rehearsed speeches.'],
];
const medicalPoints = ['Eyesight and colour vision', 'BMI, stamina and general fitness', 'Dental health and treatment', 'Hearing, posture and old injuries', 'Sleep, nutrition and recovery habits'];
const routeMatrix = [
  ['Earliest entry', 'NDA', 'Any stream for Army wing; longest training'],
  ['Technical after Class 12', 'TES', 'PCM + 60% aggregate + JEE Main'],
  ['Graduate backup', 'CDS (IMA)', 'Any recognised graduation; PC route'],
  ['Longest age window', 'TGC', 'BE/B.Tech and strong engineering marks'],
];

function Reveal({ children, className = '' }) { return <div className={`reveal ${className}`}>{children}</div>; }
function SectionTitle({ number, kicker, title, intro }) { return <div className="section-heading"><p className="eyebrow">{number} · {kicker}</p><h2 dangerouslySetInnerHTML={{ __html: title }} /><p>{intro}</p></div>; }
function DataTable({ headers, rows, className = '' }) { return <div className={`data-table-wrap ${className}`}><table><thead><tr>{headers.map((header) => <th key={header}>{header}</th>)}</tr></thead><tbody>{rows.map((row) => <tr key={row[0]}>{row.map((cell, index) => <td className={index === 0 ? 'first-cell' : ''} key={`${row[0]}-${index}`}>{cell}</td>)}</tr>)}</tbody></table></div>; }
function EntryGuide() { return <div className="entry-guide">{entries.map((entry) => { const detail = entryDetails[entry.id]; return <article className={`entry-guide-card ${entry.accent}`} key={entry.id}><div className="entry-guide-head"><span className="entry-guide-letter">{entry.letter}</span><div><span className="entry-guide-kicker">ENTRY {entry.letter}</span><h3>{entry.name}</h3><p>{entry.fullName}</p></div><span className="entry-guide-age"><CalendarDays size={15} /> {entry.age}</span></div><div className="entry-guide-copy"><p className="entry-guide-intro">{entry.descriptor}. {detail.overview}</p><div className="entry-guide-facts"><div><span>QUALIFICATION</span><p>{entry.qualification}</p></div><div><span>SELECTION PROCESS</span><p>{detail.selection}</p></div><div><span>TRAINING & CAREER START</span><p>{detail.training}</p></div><div><span>COMMISSION</span><p>{entry.commission}</p></div></div><div className="entry-guide-deep"><div><span>WHY THIS ROUTE MATTERS</span><p>{entry.why}</p></div><div><span>HOW TO PREPARE</span><p>{detail.prepare}</p></div></div></div></article>; })}</div>; }
function PracticalGuide() { return <><section className="section practical-section" id="selection"><Reveal><SectionTitle number="07" kicker="How selection works" title={'From eligibility<br /><i>to commission.</i>'} intro="Every route has the same broad finish line: eligibility, entry filter, SSB, medical fitness, merit and joining." /></Reveal><div className="selection-grid">{selectionStages.map(([number, title, text]) => <article className="selection-card reveal" key={number}><span>{number}</span><h3>{title}</h3><p>{text}</p></article>)}</div><div className="ssb-panel reveal"><div className="ssb-heading"><p className="eyebrow">The SSB lens</p><h3>What the board is really looking for.</h3><p>There is no single perfect personality. The board is looking for a consistent pattern of officer-like qualities across different situations.</p></div><div className="ssb-list">{ssbPoints.map(([day, title, text]) => <div key={day}><span>{day}</span><div><h4>{title}</h4><p>{text}</p></div></div>)}</div></div><div className="medical-panel reveal"><div><p className="eyebrow">Protect the final mile</p><h3>Medical readiness is preparation too.</h3><p>Start routine health checks early so small issues do not become a last-minute surprise after selection.</p></div><div className="medical-list">{medicalPoints.map((point) => <span key={point}><Check size={15} />{point}</span>)}</div></div></section><section className="section matrix-section"><Reveal><SectionTitle number="08" kicker="Decision support" title={'Which route solves<br /><i>which problem?</i>'} intro="The best plan is not one exam. It is a sequence that keeps a strong first choice and a realistic fallback alive at the same time." /></Reveal><div className="matrix-grid">{routeMatrix.map(([label, route, detail]) => <div className="matrix-row" key={label}><span>{label}</span><strong>{route}</strong><p>{detail}</p><ChevronRight size={17} /></div>)}</div><div className="matrix-note reveal"><Flag size={19} /><p><strong>Planning principle:</strong> Do not choose a degree only for one exam. Choose the path that leaves the greatest number of Permanent Commission doors open while matching the student's ability and interest.</p></div></section></>; }

function App() {
  const [activeEntry, setActiveEntry] = useState('nda');
  const [menuOpen, setMenuOpen] = useState(false);
  const selectedEntry = entries.find((entry) => entry.id === activeEntry);
  useEffect(() => { const observer = new IntersectionObserver((items) => items.forEach((item) => { if (item.isIntersecting) { item.target.classList.add('is-visible'); observer.unobserve(item.target); } }), { threshold: 0.1 }); document.querySelectorAll('.reveal').forEach((item) => observer.observe(item)); return () => observer.disconnect(); }, []);
  const closeMenu = () => setMenuOpen(false);

  return <div className="site-shell">
    <header className="topbar"><a className="brand" href="#top"><span className="brand-mark"><Shield size={17} /></span><span>OFFICER <em>ROADMAP</em></span></a><button className="menu-button" onClick={() => setMenuOpen(!menuOpen)} aria-label="Toggle navigation">{menuOpen ? <X size={20} /> : <Menu size={20} />}</button><nav className={menuOpen ? 'nav-links is-open' : 'nav-links'}><a href="#overview" onClick={closeMenu}>Overview</a><a href="#routes" onClick={closeMenu}>Routes</a><a href="#calculator" onClick={closeMenu}>Calculator</a><a href="#timeline" onClick={closeMenu}>Timeline</a><a href="#strategy" onClick={closeMenu}>Strategy</a><a className="slide-download" href="/indian_army_officer_roadmap.pptx" download onClick={closeMenu}><Download size={14} /> Slides</a></nav></header>
    <main id="top">
      <section className="hero-section"><div className="hero-grid" /><div className="hero-copy reveal"><p className="eyebrow"><span className="eyebrow-line" /> Permanent Commission Planning · 2026—2038</p><h1>Indian Army<br /><i>Officer Roadmap</i></h1><p className="hero-intro">A decade-long, four-entry plan for Permanent Commission — with age windows calculated exactly against each exam's real cut-off mechanics.</p><div className="hero-actions"><a className="button button-primary" href="#overview">Begin the brief <ArrowDownRight size={17} /></a><a className="text-link" href="/indian_army_officer_roadmap.pptx" download><Download size={15} /> Download slides</a></div></div><div className="hero-aside reveal"><div className="orbit orbit-one" /><div className="orbit orbit-two" /><div className="compass"><span>N</span><span>E</span><span>S</span><span>W</span><Shield size={27} /></div><div className="hero-note"><span>01</span><p>Start with the earliest door.<br /><strong>Keep the others open.</strong></p></div></div><div className="hero-bottomline"><span>PREPARED AS A FAMILY PLANNING GUIDE</span><span className="scroll-cue"><span /> Scroll to map the journey</span><span>INDIA · PC TRACK</span></div></section>
      <section className="stats-strip"><div className="stat"><strong>4</strong><span>independent<br />PC entries</span></div><div className="stat"><strong>15<sup>+</sup></strong><span>realistic attempts<br />across a decade</span></div><div className="stat"><strong>2028</strong><span>first real NDA<br />attempt</span></div><div className="stat stat-note"><Sparkles size={18} /><span>Permanent Commission<br /><strong>from every route</strong></span></div></section>

      <section className="section overview-section" id="overview"><Reveal><SectionTitle number="01" kicker="Overview" title={'What this plan<br /><i>covers.</i>'} intro="This is a complete route map from Class 10 through the final graduate-entry window. The plan is built around one DOB: 20 September 2011, currently Class 10 (2026–27)." /></Reveal><div className="overview-grid">{[['1', 'The Four PC Entries', 'NDA, TES, CDS (IMA) and TGC — how each one works'], ['2', 'Why September Matters', 'How the real age cut-off mechanics shift exact attempts'], ['3', 'Age & Attempt Calculator', 'Exact eligibility windows, recalculated precisely'], ['4', 'Year-by-Year Timeline', 'Every stage from Class 10 (now) to age 27 (2038)'], ['5', 'Preparation Roadmap', 'What to focus on stage by stage, starting now'], ['6', 'Strategy by Phase', 'What to prioritise, and when, across three phases'], ['7', 'The Complete Journey', 'A visual walk-through from school to commissioning'], ['8', 'Final Takeaways', 'The single best path for maximum PC chances']].map(([number, title, text]) => <div className="overview-item" key={number}><span>{number}</span><div><h3>{title}</h3><p>{text}</p></div></div>)}</div></section>

      <section className="section routes-section" id="routes"><Reveal><SectionTitle number="02" kicker="The four PC entries" title={'One destination.<br /><i>Four ways in.</i>'} intro="Each entry is a different kind of opening. Together, they create a first choice, a parallel play and a long runway." /></Reveal><div className="route-layout"><div className="route-list reveal">{entries.map((entry) => <button key={entry.id} className={activeEntry === entry.id ? `route-row active ${entry.accent}` : 'route-row'} onClick={() => setActiveEntry(entry.id)} type="button"><span className="route-letter">{entry.letter}</span><span><b>{entry.name}</b><small>{entry.fullName}</small></span><ChevronRight size={19} /></button>)}</div><div className={`route-detail ${selectedEntry.accent} reveal`} key={selectedEntry.id}><div className="detail-top"><span className="detail-kicker">ENTRY {selectedEntry.letter}</span><span className="detail-window"><CalendarDays size={15} /> {selectedEntry.age}</span></div><h3>{selectedEntry.fullName}</h3><p className="detail-descriptor">{selectedEntry.descriptor}</p><div className="detail-facts"><div><span>QUALIFICATION</span><strong>{selectedEntry.qualification}</strong></div><div><span>SELECTION</span><strong>{selectedEntry.selection}</strong></div><div><span>TRAINING</span><strong>{selectedEntry.training}</strong></div><div><span>COMMISSION</span><strong>{selectedEntry.commission}</strong></div></div><div className="why-box"><Target size={18} /><div><span>{selectedEntry.whyTitle}</span><p>{selectedEntry.why}</p></div></div></div></div><EntryGuide /></section>

      <section className="section september-section"><Reveal><SectionTitle number="03" kicker="The fix" title={'Why September<br /><i>matters.</i>'} intro="UPSC does not check age on the exam date — it checks age on the day the course actually starts (1 Jan or 1 Jul for NDA). That fixed reference point, not his birthday's position in the calendar, decides which sittings count." /></Reveal><div className="attempt-rail reveal"><div className="rail-line" />{[['NDA II 2027', 'Sept 2027', false], ['NDA I 2028', 'Apr 2028', false], ['NDA II 2028', 'Sept 2028', true], ['NDA I 2029', 'Apr 2029', true], ['NDA II 2029', 'Sept 2029', true], ['NDA I 2030', 'Apr 2030', true]].map(([title, sub, ok], index) => <div className={ok ? 'rail-point ok' : 'rail-point'} key={title}><span className="rail-dot" /><div><strong>{title}</strong><small>{sub}</small>{index === 2 && <b>FIRST REAL SHOT</b>}</div></div>)}</div><div className="legend-row"><span><i className="legend-dot green" /> Age-eligible AND academically qualified — a real, usable attempt</span><span><i className="legend-dot gray" /> Age-eligible, but still in Class 11 — not academically qualified yet</span></div><div className="result-callout"><strong>Net result: 4 real attempts, not 3 or 6</strong><span>NDA II 2028, NDA I 2029, NDA II 2029, NDA I 2030. TES follows the same twice-yearly rhythm alongside these.</span></div></section>

      <section className="section calculator-section" id="calculator"><Reveal><SectionTitle number="04" kicker="Planning data" title={'Age & attempt<br /><i>calculator.</i>'} intro="Based on DOB 20 September 2011, currently Class 10 (2026–27)." /></Reveal><DataTable headers={['Entry', 'Eligibility (age)', 'Exact Age Window', 'Realistic Attempts', 'Which Sittings']} rows={attempts} className="reveal" /><div className="key-takeaway reveal"><h3>Key Takeaway</h3><p>Because he is already in Class 10, his first real NDA/TES shot lands in September 2028 — not 2029. CDS and TGC windows are pure age arithmetic from his birthday, but their exact calendar edges can shift by up to 6 months depending on the notification, so treat those two as directional and reconfirm closer to the date.</p></div></section>

      <section className="section timeline-section" id="timeline"><Reveal><SectionTitle number="05" kicker="Planning data" title={'Year-by-year<br /><i>timeline.</i>'} intro="Every stage from Class 10 now through the final graduate-entry cycle in 2038." /></Reveal><div className="timeline-tables"><div className="timeline-block reveal"><div className="block-label">PART 1 OF 2 · 2026–2032</div><DataTable headers={['Year', 'Age', 'Stage', 'Exams He Can Attempt', 'Notes']} rows={timelineA} /></div><div className="timeline-block reveal"><div className="block-label">PART 2 OF 2 · 2033–2038</div><DataTable headers={['Year', 'Age', 'Stage', 'Exams He Can Attempt', 'Notes']} rows={timelineB} /></div></div></section>

      <section className="section prep-table-section" id="preparation"><Reveal><SectionTitle number="06" kicker="Getting ready" title={'Preparation roadmap<br /><i>by stage.</i>'} intro="What to actually focus on, starting now — not just which exams to sit." /></Reveal><DataTable headers={['Stage', 'Focus Areas']} rows={prepRows} className="reveal" /></section>

      <PracticalGuide />

      <section className="section strategy-section" id="strategy"><Reveal><SectionTitle number="07" kicker="Strategy by phase" title={'The plan gets<br /><i>stronger with time.</i>'} intro="The recommendation is sequential: attack the broadest door first, protect the technical fallback, then run graduate entries together." /></Reveal><div className="strategy-blocks"><Reveal><div className="phase-heading"><span>1</span><div><h3>Phase 1 — School-Leaving Attempts (2028–2030)</h3><p>Go for both NDA and TES, starting with NDA II in September 2028.</p></div></div><div className="strategy-cards">{strategyOne.map(([title, text]) => <article key={title}><span className="gold-bar" /><h4>{title}</h4><p>{text}</p></article>)}</div></Reveal><Reveal><div className="phase-heading"><span>2</span><div><h3>Phase 2 — Choosing His Degree Wisely (2029 onward)</h3><p>Enroll in 2029 after boards — even while still attempting NDA I 2030 as a parallel shot.</p></div></div><div className="degree-grid"><article className="recommended"><h4>Engineering Degree (B.Tech / BE)</h4><b>RECOMMENDED</b><p>Keeps BOTH CDS and TGC open. The strictly safer choice — it does not shut any Permanent Commission door. Ideally Electronics / Comm / CS / IT if he is drawn to Signals.</p></article><article><h4>Non-Engineering Degree (BA / BSc / BCom)</h4><p>Keeps only CDS open — TGC needs an engineering degree, so this path closes one of his four doors early.</p></article></div><div className="phase-banner">Recommendation: choose engineering — it is strictly the safer choice since it does not shut any PC door.</div></Reveal><Reveal><div className="phase-heading"><span>3</span><div><h3>Phase 3 — Graduate-Entry Attempts (2032–2038) & Backup Plan</h3></div></div><div className="backup-grid"><article><h4>Go for CDS and TGC together</h4><p>Attempt CDS and TGC simultaneously every cycle from his final year onward (provisional applications are allowed). TGC has the shorter, faster training (1 year) with bonus seniority; CDS-IMA is the broader graduate entry. This phase alone gives him well over 10 combined attempts across several years.</p></article><article><h4>Backup Plan</h4><p>Even if NDA and TES do not come through by 2030, the CDS / TGC window (2032–2038) is wide and forgiving — well over 15 realistic attempts across all four entries over his whole eligible life if he stays consistent.</p></article></div></Reveal></div></section>

      <section className="section journey-section"><Reveal><SectionTitle number="08" kicker="Roadmap" title={'The complete<br /><i>journey.</i>'} intro="The entire path in one view: school, first attempts, degree fallback, graduate entries, SSB and commissioning." /></Reveal><div className="journey-flow reveal"><div className="journey-row">{[['Class 10', 'Now, 2026–27'], ['Class 11', '2027–28'], ['Class 12', '2028–29'], ["NDA II'28 · NDA I&II'29", 'UPSC or PCM% + JEE'], ['SSB + Medical', 'Interview & board']].map(([title, sub], index) => <div className="flow-step" key={title}><strong>{title}</strong><small>{sub}</small>{index < 4 && <ChevronRight size={15} />}</div>)}</div><div className="journey-branches"><div className="flow-selected"><strong>SELECTED</strong><span>3–4 yrs training @ NDA/CME + IMA</span><b>Commissioned as Lt (PC) — Arm of choice</b></div><span className="or-label">or, if not selected →</span><div className="flow-fallback"><strong>Engineering Degree</strong><span>2029/30 — 2033, keeps CDS + TGC open</span></div><ChevronRight size={18} /><div className="flow-fallback"><strong>CDS (IMA) & TGC</strong><span>Final year onward, 2032–2038</span></div></div><div className="journey-end"><span>SSB Interview + Medical Board</span><ChevronRight size={18} /><strong>Commissioned as Lt — Permanent Commission</strong></div></div></section>

      <section className="final-section"><div className="final-inner"><div className="final-top"><p className="eyebrow">09 · Final takeaway</p><h2>The best possible path<br /><i>for maximum PC chances.</i></h2></div><div className="final-stats"><div><strong>4</strong><span>Independent PC entries</span></div><div><strong>15<sup>+</sup></strong><span>Realistic attempts</span></div><div><strong>2028—2038</strong><span>Full eligibility window</span></div></div><div className="final-list">{finalTakeaways.map((line) => <p key={line}><Check size={17} />{line}</p>)}</div><p className="disclaimer">Reminder: NDA age mechanics above are confirmed against the standard UPSC pattern; CDS/TGC calendar edges can shift ±6 months by notification. Always confirm exact dates against the official UPSC / Indian Army notification each year.</p></div></section>
    </main>
    <footer className="footer"><span>OFFICER <em>ROADMAP</em></span><span>Confirm exact cut-offs each cycle at joinindianarmy.nic.in and upsc.gov.in</span><span>PC TRACK · 2026</span></footer>
  </div>;
}

createRoot(document.getElementById('root')).render(<StrictMode><App /></StrictMode>);
